security:
  oauth2:
    client:
      clientId: your-onelogin-oidc-app-client-id
      clientSecret: your-onelogin-oidc-app-client-secret
      accessTokenUri: https://openid-connect.onelogin.com/oidc/token
      userAuthorizationUri: https://openid-connect.onelogin.com/oidc/auth
      tokenName: access_token
      authorizedGrantTypes: authorization_code
      authenticationScheme: form
      clientAuthenticationScheme: form
      scope: openid,profile,email
    resource:
      userInfoUri: https://openid-connect.onelogin.com/oidc/me

server:
  port : 8081
